### ISSUE TITLE
Feature request: Support tar files missing directory entries

### ISSUE THREAD

**Issue by nlepage** [nlepage/go-tarfs#12]
Some tar files may have file entries with a path inside of a directory (eg `dir1/file11`), but miss corresponding directory entries (eg have no entry for `dir1`).

ping @mihaibuzgau @viovanov I saw both of you had forks to support this, I just released a [v1.1.0](https://github.com/nlepage/go-tarfs/releases/tag/v1.1.0) which supports this.

**Comment by viovanov** [comment]
Amazing, thanks @nlepage !
